name:                block-puzzle
version:             0.1.0.0
github:              "githubuser/block-puzzle"
license:             BSD3
author:              "Yuji Yokoo"
maintainer:          "yujiyokoo@gmail.com"
copyright:           "2021 Yuji Yokoo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/block-puzzle#readme>

dependencies:
- base >= 4.7 && < 5
- time
- Yampa
- sdl2
- listsafe
- ilist

library:
  source-dirs: src

executables:
  block-puzzle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - block-puzzle

tests:
  block-puzzle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - block-puzzle
